# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-04 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=40)),
                ('idnumber', models.CharField(max_length=50)),
            ],
        ),
    ]
